"""
Django settings for bangaidj project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

try:
    from .logging import LOGGING  # Correct import statement
except ImportError:
    LOGGING = {}  # Set an empty dictionary if logging.py is not found

# Assign the imported LOGGING dictionary to settings.LOGGING
LOGGING = LOGGING

from dotenv import load_dotenv
from django.conf import settings
load_dotenv()
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

from django.conf.global_settings import DATETIME_INPUT_FORMATS, DATE_INPUT_FORMATS



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$z5zdwvb)%5fn4m!353c5l7ao83h8ev@e=t+zplu(jyowyz&t0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['202.168.250.137', '127.0.0.1', 'WIN-PV48JSSIEMF.DOMAIN.local:8000']
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'bootstrap_datepicker_plus',
    'bootstrap4',
    'crispy_bootstrap4',

    'django_extensions',
    'tinymce',
    'django_ckeditor_5',

'audit_workflow.apps.AuditWorkflowConfig',

    'BranchInspection',

    'crispy_forms',
    'django_filters',

    'django_forms_bootstrap',

    'formtools',
    'main',

    'django.contrib.humanize',
    'budget_register',

    'rest_framework',



]

#AUTH_USER_MODEL = 'audit_management.User' # changes build in user model
AUTH_USER_MODEL = 'audit_workflow.User' # changes build in user model

# Explicit session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default database-backed sessions
SESSION_COOKIE_NAME = 'sessionid'  # Default cookie name
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Set True if sessions should expire on browser close
SESSION_COOKIE_SECURE = False  # Set True for HTTPS
SESSION_SAVE_EVERY_REQUEST = False  # Save session only when modified

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'bangaidj.urls'
CRISPY_TEMPLATE_PACK = 'bootstrap4'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'bangaidj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'django_audit_workflow',  # Your database name
#         'USER': 'django_user',  # Your PostgreSQL user
#         'PASSWORD': 'hibiJibi49',  # Your PostgreSQL password
#         'HOST': 'localhost',  # Keep 'localhost' for local development
#         'PORT': '5432',  # Default PostgreSQL port
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = True

USE_TZ = True
DATE_INPUT_FORMATS = ['%Y-%m-%d']
# DATE_INPUT_FORMATS += ('%Y-%m-%d', "%d-%m-%Y",)
# DATETIME_INPUT_FORMATS += ("%d-%m-%Y %H:%M:%S",)



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [ ]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # 'static' directory at the project root


PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

#STATIC_ROOT = os.path.join(PROJECT_DIR, '../../static')



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CKEDITOR_UPLOAD_PATH = "uploads/"

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


CSRF_COOKIE_SECURE = False  # Set this to True if using HTTPS
CSRF_COOKIE_HTTPONLY = True


#OPENWEATHER_API_KEY = os.getenv("37e4640dec87372ab552f548")
#WEATHERAPI_API_KEY = os.getenv("cur_live_j6kWdKdhKlLDlVAlz5GbDQy4dMz1gqM5bVRJh5w3")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.krishibank.org.bd'
EMAIL_PORT = 25
EMAIL_HOST_USER = 'noreply_ictop@krishibank.org.bd'
EMAIL_HOST_PASSWORD = 'auto@7654321*'
EMAIL_USE_TLS = False  # MAIL_ENCRYPTION=null
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = 'noreply_ictop@krishibank.org.bd'


#LOGIN_URL = 'audit_workflow:login'
LOGIN_REDIRECT_URL = 'main:home'
LOGOUT_REDIRECT_URL = 'audit_workflow:login'