# Generated by Django 5.1.5 on 2025-02-09 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('branch_code', models.IntegerField(null=True)),
                ('region', models.CharField(max_length=250, null=True)),
                ('division', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('regular', 'Regular User')], default='regular', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(blank=True, max_length=250, null=True)),
                ('branch_code', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('division', models.CharField(blank=True, max_length=250, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='internal_audit_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='internal_audit_users_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submitted', models.BooleanField(default=False)),
                ('submission_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_workflow.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(default=0, max_length=10)),
                ('case_description', models.CharField(blank=True, max_length=50, null=True)),
                ('case_filed_at', models.DateField()),
                ('case_status', models.CharField(choices=[('নিষ্পন্ন', 'নিষ্পন্ন'), ('অনিষ্পন্ন', 'অনিষ্পন্ন')], default='অনিষ্পন্ন', max_length=100)),
                ('amount', models.BigIntegerField(default=0)),
                ('Branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_workflow.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('current_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='audit_workflow.items')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, max_length=1500, null=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='audit_workflow.comment')),
                ('case_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='audit_workflow.objection')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('comment', 'Comment'), ('decision', 'Decision'), ('pass', 'Pass')], max_length=20)),
                ('action_details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='audit_workflow.objection')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('run', 'Run'), ('close', 'Close')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='audit_workflow.objection')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=10)),
                ('pf', models.CharField(blank=True, max_length=50, null=True)),
                ('accused_time_post', models.CharField(blank=True, max_length=50, null=True)),
                ('current_post', models.CharField(blank=True, max_length=50, null=True)),
                ('accusing_time', models.DateField(blank=True, null=True)),
                ('accusing_tenure', models.CharField(blank=True, max_length=15)),
                ('accusing_time_branch', models.CharField(max_length=25)),
                ('current_branch', models.CharField(max_length=25)),
                ('case_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit_workflow.objection')),
            ],
        ),
        migrations.CreateModel(
            name='AuditObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.CharField(blank=True, choices=[('Memo', 'Memo'), ('Part-1', 'Part-1'), ('Part-2', 'Part-2'), ('Part-3', 'Part-3')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_workflow.auditsubmission')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit_workflow.items')),
                ('related_persons', models.ManyToManyField(blank=True, to='audit_workflow.person')),
            ],
        ),
        migrations.CreateModel(
            name='Personel_Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isEmployee_involve', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=50)),
                ('case_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_workflow.objection')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='ডকুমেন্টের বর্ণনাঃ')),
                ('document', models.FileField(upload_to='media/internal_audit/%Y/%m/%d', verbose_name='ডকুমেন্ট সংযুক্তকরণঃ')),
                ('is_first', models.BooleanField(default=False)),
                ('upload_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_workflow.objection')),
            ],
        ),
    ]
