# Generated by Django 5.1.5 on 2025-02-11 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_statuses', to='audit_workflow.auditsubmission')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_workflow.items')),
            ],
            options={
                'unique_together': {('audit', 'item')},
            },
        ),
    ]
