# Generated by Django 5.1.5 on 2025-02-17 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0002_audititemstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='case_no',
        ),
        migrations.AddField(
            model_name='comment',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='audit_workflow.auditsubmission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditobjection',
            name='related_persons',
            field=models.ManyToManyField(blank=True, null=True, to='audit_workflow.person'),
        ),
    ]
