# Generated by Django 5.1.5 on 2025-02-23 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0005_auditsubmission_year_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comment_files/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='audit_workflow.items'),
            preserve_default=False,
        ),
    ]
