# Generated by Django 5.1.5 on 2025-02-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0006_comment_file_alter_comment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditobjection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
