# Generated by Django 5.1.5 on 2025-02-27 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0008_alter_user_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='is_first',
        ),
        migrations.AlterField(
            model_name='upload',
            name='document',
            field=models.FileField(upload_to='media/audit_workflow/%Y/%m/%d', verbose_name='ডকুমেন্ট সংযুক্তকরণঃ'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='audit_workflow.auditobjection'),
        ),
    ]
