# Generated by Django 5.1.5 on 2025-02-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0009_remove_upload_is_first_alter_upload_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='document',
            field=models.FileField(upload_to='audit_workflow/%Y/%m/%d', verbose_name='ডকুমেন্ট সংযুক্তকরণঃ'),
        ),
    ]
