# Generated by Django 5.1.5 on 2025-03-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0011_remove_person_case_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditobjection',
            name='related_persons',
        ),
    ]
