# Generated by Django 5.1.5 on 2025-03-10 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0012_remove_auditobjection_related_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='audit_objection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convicted_persons', to='audit_workflow.auditobjection'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
