# Generated by Django 5.1.5 on 2025-03-11 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0013_person_audit_objection_alter_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel_decision',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit_workflow.items'),
        ),
    ]
