# Generated by Django 5.1.5 on 2025-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0014_personel_decision_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel_decision',
            name='isEmployee_involve',
            field=models.BooleanField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', null=True),
        ),
    ]
