# Generated by Django 5.1.5 on 2025-03-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0015_alter_personel_decision_isemployee_involve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel_decision',
            name='isEmployee_involve',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
