# Generated by Django 5.1.5 on 2025-03-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0016_alter_personel_decision_isemployee_involve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='itemName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
