# Generated by Django 5.1.5 on 2025-04-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0017_alter_items_category_alter_items_itemname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectiondecision',
            name='case',
        ),
        migrations.AddField(
            model_name='objectiondecision',
            name='audit_objection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='audit_workflow.auditobjection'),
        ),
    ]
