# Generated by Django 5.1.5 on 2025-04-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0018_remove_objectiondecision_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='itemNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('regular', 'Regular User'), ('rao', 'RAO')], default='regular', max_length=20),
        ),
    ]
