# Generated by Django 5.1.5 on 2025-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0019_items_itemno_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='auditType',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('AD', 'AD'), ('ICT Audit', 'ICT Audit')], default='General', max_length=25, null=True),
        ),
    ]
