# Generated by Django 5.1.5 on 2025-04-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0020_items_audittype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='auditType',
            new_name='audit_type',
        ),
    ]
