# Generated by Django 5.1.5 on 2025-04-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0021_rename_audittype_items_audit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsubmission',
            name='audit_type',
            field=models.CharField(choices=[('General', 'General'), ('AD', 'AD'), ('ICT Audit', 'ICT Audit')], default='General', max_length=25),
        ),
        migrations.AlterField(
            model_name='auditobjection',
            name='category',
            field=models.CharField(blank=True, choices=[('Memo', 'Memo'), ('Part-2', 'Part-2'), ('Part-3', 'Part-3')], max_length=10, null=True),
        ),
    ]
