# Generated by Django 5.1.5 on 2025-05-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0022_auditsubmission_audit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bn_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
