# Generated by Django 5.1.5 on 2025-05-13 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0023_branch_bn_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsubmission',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditsubmission',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('regular', 'Regular User'), ('rao', 'RAO'), ('authorizer', 'Authorizer')], default='regular', max_length=20),
        ),
    ]
