# Generated by Django 5.1.5 on 2025-05-28 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0025_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='fixed_auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_auditor_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='fixed_authorizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_authorizer_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='fixed_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_manager_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='type',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('regional', 'Regional Office'), ('division', 'Divisional Office'), ('branch', 'Regular Branch')], default='branch', max_length=20),
        ),
    ]
