# Generated by Django 5.1.5 on 2025-06-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_workflow', '0026_branch_fixed_auditor_branch_fixed_authorizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='type',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('regional', 'Regional Office'), ('division', 'Divisional Office'), ('branch', 'Regular Branch'), ('ho', 'Head Office')], default='branch', max_length=20),
        ),
    ]
