# Generated by Django 5.1.5 on 2025-05-28 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_workflow', '0026_branch_fixed_auditor_branch_fixed_authorizer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffSiteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('branch_management', 'Branch Management'), ('cash_instrumental', 'Cash and Instrumental Transaction'), ('deposit', 'Deposit'), ('general_banking', 'General Banking'), ('accounting', 'Accounting'), ('loan_advances', 'Loan and Advances'), ('foreign_trade', 'Foreign Trade')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BranchInspectionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by_manager', models.BooleanField(default=False)),
                ('replied_by_headoffice', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_workflow.branch')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BranchInspectionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='BranchInspection.branchinspectionsubmission')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BranchInspection.offsiteitem')),
            ],
            options={
                'unique_together': {('submission', 'item', 'user')},
            },
        ),
    ]
