# Generated by Django 5.1.5 on 2025-05-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offsiteitem',
            name='name',
            field=models.TextField(),
        ),
    ]
