# Generated by Django 5.1.5 on 2025-05-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0002_alter_offsiteitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinspectioncomment',
            name='reply_by_monitoring',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchinspectioncomment',
            name='returned_by_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branchinspectioncomment',
            name='verified_by_manager',
            field=models.BooleanField(default=False),
        ),
    ]
