# Generated by Django 5.1.5 on 2025-06-01 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0003_branchinspectioncomment_reply_by_monitoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinspectionsubmission',
            name='extended_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchinspectionsubmission',
            name='month',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
