# Generated by Django 5.1.5 on 2025-06-03 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0004_branchinspectionsubmission_extended_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchinspectionsubmission',
            old_name='authorized_by_manager',
            new_name='finalized',
        ),
        migrations.RenameField(
            model_name='branchinspectionsubmission',
            old_name='replied_by_headoffice',
            new_name='is_forwarded',
        ),
        migrations.RemoveField(
            model_name='branchinspectioncomment',
            name='reply_by_monitoring',
        ),
        migrations.RemoveField(
            model_name='branchinspectioncomment',
            name='returned_by_manager',
        ),
        migrations.RemoveField(
            model_name='branchinspectioncomment',
            name='verified_by_manager',
        ),
        migrations.RemoveField(
            model_name='branchinspectionsubmission',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='branchinspectionsubmission',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='branchinspectionsubmission',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchinspectionsubmission',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branchinspectionsubmission',
            name='monitoring_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchinspectionsubmission',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchinspectionsubmission',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchinspectionsubmission',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MonitoringReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('replied_at', models.DateTimeField(auto_now_add=True)),
                ('replied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BranchInspection.branchinspectionsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BranchInspection.branchinspectionsubmission')),
            ],
        ),
    ]
