# Generated by Django 5.1.5 on 2025-06-03 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0005_rename_authorized_by_manager_branchinspectionsubmission_finalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringreply',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_replies', to='BranchInspection.branchinspectionsubmission'),
        ),
    ]
