# Generated by Django 5.1.5 on 2025-06-04 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0006_alter_monitoringreply_submission'),
        ('audit_workflow', '0026_branch_fixed_auditor_branch_fixed_authorizer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('extended_until', models.DateField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_workflow.branch')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('branch', 'month')},
            },
        ),
    ]
