# Generated by Django 5.1.5 on 2025-06-23 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0007_branchextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringreply',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_replies', to='BranchInspection.offsiteitem'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoringreply',
            unique_together={('submission', 'item')},
        ),
    ]
