# Generated by Django 5.1.5 on 2025-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0008_monitoringreply_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinspectionsubmission',
            name='return_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
