# Generated by Django 5.1.5 on 2025-07-08 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0010_regionreplyfinalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='offsiteitem',
            name='predefined_replies',
            field=models.TextField(blank=True, help_text='Separate replies by | or use JSON if needed'),
        ),
        migrations.AlterField(
            model_name='monitoringreply',
            name='replied_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
