# Generated by Django 5.1.5 on 2025-07-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0011_offsiteitem_predefined_replies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringreply',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
