# Generated by Django 5.1.5 on 2025-07-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0012_monitoringreply_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinspectionsubmission',
            name='is_reply_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
