# Generated by Django 5.1.5 on 2025-07-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BranchInspection', '0013_branchinspectionsubmission_is_reply_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offsiteitem',
            name='item_no',
            field=models.CharField(max_length=20),
        ),
    ]
